services:
  calendo-fe:
    build: .
    image: calendo-fe:latest
    container_name: calendo-fe
    ports:
      - "3002:80"
    networks:
      - calendo-network
    restart: always

networks:
  calendo-network:
    name: calendo-network
    external: true 