services:
  backend:
    build: .
    container_name: calendo-backend
    ports:
      - "8080:8080"
    environment:
      - N8N_API_URL=http://n8n:5678
      - N8N_API_KEY=${N8N_API_KEY}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    networks:
      - calendo-network
    restart: unless-stopped

volumes:
  postgres_data:
    name: calendo-postgres-data

networks:
  calendo-network:
    name: calendo-network
    external: true 