version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: calendo-db
    environment:
      POSTGRES_DB: calendo
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - calendo-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d calendo"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: calendo-postgres-data

networks:
  calendo-network:
    name: calendo-network
    driver: bridge 