services:
  n8n:
    image: n8nio/n8n
    container_name: calendo-be
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=5678
      - N8N_PROTOCOL=${N8N_PROTOCOL}
      - DB_TYPE=postgresdb
      - DB_POSTGRES_HOST=${POSTGRES_HOST}
      - DB_POSTGRES_DATABASE=${POSTGRES_DB}
      - DB_POSTGRES_USER=${POSTGRES_USER}
      - DB_POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
    networks:
      - calendo-network
    restart: unless-stopped

  backend:
    build: .
    container_name: calendo-backend
    ports:
      - "8080:8080"
    environment:
      - N8N_API_URL=http://n8n:5678
      - N8N_API_KEY=${N8N_API_KEY}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    networks:
      - calendo-network
    restart: unless-stopped

volumes:
  postgres_data:
    name: calendo-postgres-data

networks:
  calendo-network:
    name: calendo-network
    external: true 