services:
  calendo-be:
    build:
      context: .
      dockerfile: Dockerfile
    image: calendo-be:latest
    container_name: calendo-be
    ports:
      - "8080:8080"
    env_file:
      - ../.env
    networks:
      - calendo-net
    restart: unless-stopped

volumes:
  postgres_data:
    name: calendo-postgres-data

networks:
  calendo-net:
    name: calendo-net
    external: true